//
// Generated file, do not edit! Created by opp_msgtool 6.0 from MessageFrame.msg.
//

#ifndef __MESSAGEFRAME_M_H
#define __MESSAGEFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MessageFrame;
// cplusplus {{
   #include <string>
//   #include <bitset>
//   typedef std::bitset<8> bits;
// }}

/**
 * Class generated from <tt>MessageFrame.msg:25</tt> by opp_msgtool.
 * <pre>
 * //class noncobject bits;
 * //
 * // TODO generated message class
 * //
 * packet MessageFrame
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int seqNum;
 *     string payload;
 *     char parity;
 *     //	bits parity;
 *     int frameType;
 *     int ackNum;
 * }
 * </pre>
 *
 * MessageFrame_Base is only useful if it gets subclassed, and MessageFrame is derived from it.
 * The minimum code to be written for MessageFrame is the following:
 *
 * <pre>
 * class MessageFrame : public MessageFrame_Base
 * {
 *   private:
 *     void copy(const MessageFrame& other) { ... }

 *   public:
 *     MessageFrame(const char *name=nullptr, short kind=0) : MessageFrame_Base(name,kind) {}
 *     MessageFrame(const MessageFrame& other) : MessageFrame_Base(other) {copy(other);}
 *     MessageFrame& operator=(const MessageFrame& other) {if (this==&other) return *this; MessageFrame_Base::operator=(other); copy(other); return *this;}
 *     virtual MessageFrame *dup() const override {return new MessageFrame(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from MessageFrame_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(MessageFrame)
 * </pre>
 */
class MessageFrame_Base : public ::omnetpp::cPacket
{
  protected:
    int seqNum = 0;
    std::string payload;
    char parity = 0;
    int frameType = 0; //Data=0, ACK=1, NACK=2.
    int ackNum = 0;

  private:
    void copy(const MessageFrame_Base& other);

  protected:
    bool operator==(const MessageFrame_Base&) = delete;

  public:
    // make constructors protected to avoid instantiation
    MessageFrame_Base(const char *name=nullptr, short kind=0);
    MessageFrame_Base(const MessageFrame_Base& other);
    // make assignment operator protected to force the user override it
    MessageFrame_Base& operator=(const MessageFrame_Base& other);
    virtual ~MessageFrame_Base();
    virtual MessageFrame_Base *dup() const override {
        return new MessageFrame_Base(*this);
    }
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);

    virtual std::string getPayload() const;
    virtual void setPayload(std::string payload);

    virtual char getParity() const;
    virtual void setParity(char parity);

    virtual int getFrameType() const;
    virtual void setFrameType(int frameType);

    virtual int getAckNum() const;
    virtual void setAckNum(int ackNum);
};


namespace omnetpp {

template<> inline MessageFrame_Base *fromAnyPtr(any_ptr ptr) { return check_and_cast<MessageFrame_Base*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGEFRAME_M_H

